name 'formatron_redis'
version '0.1.1'
description 'Formatron Redis cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/redis-cookbook'
issues_url 'https://github.com/formatron/redis-cookbook/issues'
supports 'ubuntu'
